### ISSUE TITLE
Port from modules to RcppR6

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant#86]
Motivation for this is to avoid the long load time, allow using devtools, and allow templated plant types.  This will also remove the virtual functions/inheritence in the low-level things, which will clean things up a little.

RcppR6 looks about ready: the main thing required will be default arguments as the current implementation does not support these, and will never support multiple constructors.  Converting things will take a little while though.  Here's an example (untested) switching the Interpolator class:

``` c++
  Rcpp::class_<interpolator::Interpolator>("Interpolator")
    .constructor()
    .constructor<bool,bool>()
    .property("type",     &interpolator::Interpolator::type)
    .method("init",       &interpolator::Interpolator::init)
    .method("eval",       &interpolator::Interpolator::r_eval)
    .method("deriv",      &interpolator::Interpolator::r_deriv)
    .property("x",        &interpolator::Interpolator::get_x)
    .property("y",        &interpolator::Interpolator::get_y)
    .property("xy",       &interpolator::Interpolator::r_get_xy)
    .property("size",     &interpolator::Interpolator::size)
    .property("min",      &interpolator::Interpolator::min)
    .property("max",      &interpolator::Interpolator::max)
    ;
```

``` yml
Interpolator:
  roxygen: @export
  name_cpp: interpolator::Interpolator
  constructor:
    # Need defaults to make this work nicely:
    args: [is_akima: bool=TRUE, is_linear: bool=TRUE]
  methods:
    init:
      args: [x: "const std::vector<double>&", 
        y: "const std::vector<double>&"]
      return_type: void
    eval: 
      name_cpp: r_eval
      args: [x: "std::vector<double>"]
      return_type: "std::vector<double>"
    deriv:
      name_cpp: r_deriv
      args: [x: "std::vector<double>"]
      return_type: "std::vector<double>"
  active:
    type: {type: std::string, access: method}
    x: {type: "std::vector<double>", access: member, name_cpp: get_x}
    y: {type: "std::vector<double>", access: member, name_cpp: get_y}
    xy: {type: "Rcpp::NumericMatrix", type: member, name_cpp: get_xy}
    size: {type: size_t, access: member}
    min: {type: double, access: member}
    max: {type: double, access: member}
```
